language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t toha70/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true toha70/react-test npm run test

after_success:
    - docker build -t toha70/mutli-nginx ./nginx
    - docker build -t toha70/multi-client ./client
    - docker build -t toha70/multi-api ./api
    - docker build -t toha70/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    - docker push toha70/multi-client
    - docker push toha70/multi-api
    - docker push toha70/mutli-nginx
    - docker push toha70/multi-worker

